export async function GET() {
  const URL = process.env.NEXT_PUBLIC_URL || "https://traingo.xyz"
  
  return Response.json({
    "accountAssociation": {
      "header": "eyJmaWQiOjEzNDk5OTMsInR5cGUiOiJhdXRoIiwia2V5IjoiMHgzMzM0QjEyMjNjMTEzOGIzOUEzOWI0YjUyOTllNmRGZDRmM2ZjQ2JGIn0",
      "payload": "eyJkb21haW4iOiJ0cmFpbmdvLnh5eiJ9",
      "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAX_E31LD9zUncowx89X5XigJtJ4kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcQfrZSMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAzNLEiPBE4s5o5tLUpnm39Tz_MvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAzNLEiPBE4s5o5tLUpnm39Tz_MvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVu4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALcbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGp2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxCwqvR4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJA8PPyQAAAAAAAAAAAAAAAC06boQXjDO7P8l_vgI7uviFbRnFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAA下乡AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW_cPk-dYmBLIhSBsfAHkzLkCEyeDAMZBYQ锯Vi-HSFXZSPv3T7Vo4iv «R0m2IhnhEm6mFYvyslnecXGjtzTj0_MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJfGYCGstsXJWcxvEVmc7lrzvI_UdH7rN18Q3nvZUZVcvHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAinsidHlwZSI6IndlYmF1YXRobi5nZXQiLCJjaGFsbGVuZ2UiOiJiTENaXzBhZ0lrT1JNS0dGenFJTEs0em5IS0JqeE1XSS0ySHQ1cGZwVnlZIiwib3JpZ2luIjoiaHR0cHM6Ly9rZXlzLmNvaW5iYXNlLmNvbSIsImNyb3NzT3JpZ2luIjpmYWxzZX0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5z2yH_BhGAfLCG_w0DUK_Lg1x75UA9T0IaqrNW-FlK9ZEK6y2v4o9lSuyhI3wAkMhN-HtJcnZdNe7WYbc4WiAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiT3B0OWUydGpxSVpoemZmdWdTVkcyWWFBU05md2dMdWhiSkRsTlY3WXZUTSIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS"
    },
    "miniapp": {
      "version": "1",
      "name": "Ready Go",
      "homeUrl": URL,
      "iconUrl": `${URL}/icon.png`,
      "splashImageUrl": `${URL}/splash-image.png`,
      "splashBackgroundColor": "#1a1a1a",
      "webhookUrl": `${URL}/api/webhook`,
      "subtitle": "Train Reaction Speed",
      "description": "A reaction training app for armwrestling athletes. Improve your start time with randomized audio signals and customizable intervals.",
      "screenshotUrls": [
        `${URL}/screenshot1.png`
      ],
      "primaryCategory": "health-fitness",
      "tags": ["reaction", "training", "armwrestling", "sports", "fitness"],
      "heroImageUrl": `${URL}/hero-image.png`,
      "tagline": "React Faster, Win More",
      "ogTitle": "Ready Go - Reaction Trainer",
      "ogDescription": "Train your reaction speed for armwrestling with randomized audio signals.",
      "ogImageUrl": `${URL}/og-image.png`,
      "noindex": false
    }
  })
}
